# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$directory\
[](fg:color_bg1 bg:color_aqua)\
$git_branch\
$git_status\
$nodejs\
$python\
[](fg:color_aqua)\
$fill\
[](fg:color_bg1)\
$username\
[@](bg:color_bg1 fg:color_fg0)\
$hostname\
$time\
$line_break\
$character\
"""
palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#8aacf4'
color_blue2 = '#00aefd'
color_aqua = '#458588'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[username]
show_always = true
style_user = "bg:color_bg1 fg:color_fg0"
style_root = "bg:color_bg1 fg:color_red"
format = '[ $user]($style)'

[hostname]
ssh_only = false
style = "bg:color_bg1 fg:color_fg0"
format = '[$hostname ]($style)'

[directory]
fish_style_pwd_dir_length = 1
style = "fg:color_blue2 bg:color_bg1"
format = "[ $path ]($style)[$read_only]($read_only_style)"
truncation_length = 3
truncation_symbol = "…/"
read_only="󰌾 "
read_only_style = "bg:color_bg1 fg:color_yellow"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:color_aqua fg:color_fg0"
format = '[ $symbol $branch]($style)'

[git_status]
style = "bg:color_aqua fg:color_bg1"
format = '[ $all_status$ahead_behind]($style)'

[nodejs]
style = "bg:color_bg1"
format = "[ $symbol$version]($style)"
version_format="(v$major.$minor)"

[time]
disabled = false
style = "fg:color_blue bg:color_bg1"
format = '[$time ]($style)'
time_format = "%R"
